### ISSUE TITLE
FEATURE: python manage.py --down/-d [profile]

### ISSUE THREAD

**Issue by agy-why** [triole/dq-dev#1]
# Context

putting down a system from docker compose is quite straight forward:
```bash
docker-compose down
```

However since the user uses `python manage.py -r` to `build` and `run` the services, it make sense to also provide an interface to put it down.

Additionally, cleaning the setup is *NOT* straight forward. Indeed the names of the container and volumes may not be sufficiently explicit or at least their relations. Therefore an interface to clean the docker service after down is a necessary feature.

# Request

```bash
python manage.py --down/-d [profile] 
```

To put down the services.

```bash
python manage.py --remove-images/--rmi [[IMAGE], [IMAGE]...]
python manage.py --remove-all-images

python manage.py --remove-volume/--rmv [[VOLUME], [VOLUME] ...]
python manage.py --remove-all-volume
```

to selectively remove the artefacts.

**Comment by triole** [comment]
I believe by now we have something like this. There was a down switch implemented two weeks https://github.com/triole/dq-dev/commit/64c12fe61bc912c04c64b34ec22c9f90d5812617 after you told us that it was missing. Maybe it is time to close this issue now. So if it is okay for you I would like to do this. Any other suggestions or improvements?
