### ISSUE TITLE
install-custom.sh should be called after wordpress setup

### ISSUE THREAD

**Issue by roerch** [triole/dq-dev#3]
in the drun.sh (docker/daiquiri/rootfs) the section which calls the install-custom script should be moved after the init-wordpress part, since (at least for 4MOST) it might be needed to install additional WP plugins in the custom script. For this to work, the wp-config.php needs to exist beforehand.

**Comment by triole** [comment]
Thanks for telling us. Fixed in d55c440aaadfeb5b0698ce921f769f64b51572ad
